# Generated by Django 5.1.6 on 2025-12-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostUserActivityCountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('save_count', models.PositiveIntegerField(default=0)),
                ('apply_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'job_post_user_activity_count',
                'description': 'Job Post User Activity Count',
            },
        ),
        migrations.CreateModel(
            name='JobPostUserEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('apply', 'Apply'), ('save', 'Save'), ('view', 'View'), ('unsave', 'Unsave'), ('share', 'Share'), ('report', 'Report'), ('bookmark', 'Bookmark')], max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_date_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_post_user_event',
                'description': 'Job Post User Event',
            },
        ),
        migrations.CreateModel(
            name='JobPostUserStateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_saved', models.BooleanField(default=False)),
                ('save_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied')], max_length=50)),
            ],
            options={
                'db_table': 'job_post_user_state',
                'description': 'Job Post User State',
            },
        ),
    ]
