# Generated by Django 5.1.6 on 2025-12-11 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity_tracking_app', '0001_initial'),
        ('auth_oauth', '0001_initial'),
        ('job_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostuseractivitycountmodel',
            name='job_post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_activity_count', to='job_management_app.jobpostmodel'),
        ),
        migrations.AddField(
            model_name='jobpostusereventmodel',
            name='job_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_management_app.jobpostmodel'),
        ),
        migrations.AddField(
            model_name='jobpostusereventmodel',
            name='user_company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_oauth.usercompanyprofile'),
        ),
        migrations.AddField(
            model_name='jobpostuserstatemodel',
            name='job_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='job_management_app.jobpostmodel'),
        ),
        migrations.AddField(
            model_name='jobpostuserstatemodel',
            name='user_company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_oauth.usercompanyprofile'),
        ),
        migrations.AddIndex(
            model_name='jobpostusereventmodel',
            index=models.Index(fields=['user_company_profile_id', 'job_post_id', 'activity_type'], name='job_post_us_user_co_02f4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpostusereventmodel',
            index=models.Index(fields=['activity_type', 'create_date'], name='job_post_us_activit_9c7d30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobpostusereventmodel',
            unique_together={('user_company_profile', 'job_post', 'activity_type', 'create_date')},
        ),
    ]
