# Generated by Django 5.1.6 on 2025-12-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('write_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_uid', models.IntegerField(blank=True, editable=False, null=True)),
                ('write_uid', models.IntegerField(blank=True, editable=False, null=True)),
                ('create_ucp_id', models.CharField(blank=True, editable=False, null=True)),
                ('write_ucp_id', models.CharField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('mail_from', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('specific_type', models.CharField(blank=True, default='', max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mail_template',
            },
        ),
        migrations.CreateModel(
            name='TotpMailConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('confirm_key', models.TextField(db_index=True, max_length=64, unique=True, verbose_name='Confirm Key')),
                ('otp_encryption', models.CharField(max_length=255, unique=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('failed_confirm', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('send_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, default='', null=True, verbose_name='The IP address of this session')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='HTTP User Agent')),
            ],
            options={
                'verbose_name': 'Email confirmation',
                'verbose_name_plural': 'Email confirmation',
                'db_table': 'auth_totp_mail',
            },
        ),
    ]
