# Generated by Django 5.1.6 on 2025-12-11 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_totp_mail', '0001_initial'),
        ('base', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplate',
            name='company',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='totpmailconfirmation',
            name='company',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_confirm_company', to='base.company'),
        ),
        migrations.AddField(
            model_name='totpmailconfirmation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_confirm_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='mailtemplate',
            index=models.Index(fields=['company'], name='mail_templa_company_b04480_idx'),
        ),
        migrations.AddIndex(
            model_name='mailtemplate',
            index=models.Index(fields=['specific_type'], name='mail_templa_specifi_e5e5a2_idx'),
        ),
        migrations.AddIndex(
            model_name='mailtemplate',
            index=models.Index(fields=['content_type', 'object_id'], name='mail_templa_content_953835_idx'),
        ),
    ]
