# Generated by Django 5.1.6 on 2026-03-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_totp_mail', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpmailconfirmation',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
