# Generated by Django 5.1.6 on 2026-03-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_totp_mail', '0003_alter_totpmailconfirmation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
