# Generated by Django 5.1.6 on 2026-05-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_totp_mail', '0004_mailtemplate_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplate',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
