# Generated by Django 5.1.6 on 2026-05-05 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_totp_mail', '0004_mailtemplate_is_active'),
        ('job_management_app', '0002_jobpostmodel_is_pipeline_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('write_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_uid', models.IntegerField(blank=True, editable=False, null=True)),
                ('write_uid', models.IntegerField(blank=True, editable=False, null=True)),
                ('create_ucp_id', models.CharField(blank=True, editable=False, null=True)),
                ('write_ucp_id', models.CharField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invitation_type', models.CharField(choices=[('invite.interview', 'Interview Invite'), ('invite.sign_contract', 'Sign Contract Invite'), ('invite.offer', 'Offer Invite'), ('invite.assessment', 'Assessment Invite')], db_index=True, max_length=20)),
                ('subject_snapshot', models.CharField(max_length=500)),
                ('body_snapshot', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('additional_message', models.CharField(blank=True, max_length=512, null=True)),
                ('location', models.CharField(blank=True, max_length=512, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geographic latitude (precision: 6 decimal places)', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geographic longitude (precision: 6 decimal places)', max_digits=9, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('job_application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='job_management_app.jobapplicationmodel')),
                ('mail_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='auth_totp_mail.mailtemplate')),
            ],
            options={
                'db_table': 'invitations',
                'indexes': [models.Index(fields=['job_application', 'invitation_type'], name='invitations_job_app_18d53c_idx'), models.Index(fields=['status'], name='invitations_status_1739b8_idx')],
            },
        ),
    ]
