# Generated by Django 5.1.6 on 2026-05-19 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_totp_mail', '0005_invitation'),
        ('auth_totp_mail', '0005_mailtemplate_description_mailtemplate_is_default_and_more'),
    ]

    operations = [
    ]
