# Generated by Django 5.1.6 on 2026-05-19 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_totp_mail', '0006_merge_20260519_0949'),
        ('job_management_app', '0005_jobpostmodel_reposted_at_jobpostmodel_reposted_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='pipeline_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='job_management_app.jobpipelineconfigmodel'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='pipeline_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='job_management_app.jobpipelineconfigstepmodel'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('DONE', 'Done')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
