# Generated by Django 5.1.6 on 2026-05-21 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_totp_mail', '0007_invitation_pipeline_config_invitation_pipeline_step_and_more'),
        ('base', '0001_initial'),
        ('job_management_app', '0005_jobpostmodel_reposted_at_jobpostmodel_reposted_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_rescheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedules', to='auth_totp_mail.invitation'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['pipeline_config', 'pipeline_step'], name='invitations_pipelin_0fdc82_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['rescheduled_from'], name='invitations_resched_2aac4d_idx'),
        ),
    ]
