# Generated by Django 5.1.6 on 2025-12-11 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('write_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_uid', models.IntegerField(blank=True, editable=False, null=True)),
                ('write_uid', models.IntegerField(blank=True, editable=False, null=True)),
                ('create_ucp_id', models.CharField(blank=True, editable=False, null=True)),
                ('write_ucp_id', models.CharField(blank=True, editable=False, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('field_name', models.CharField(blank=True, choices=[('position_title', 'Position Title'), ('employment_type', 'Employment Type'), ('job_location', 'Job Location'), ('remote_type', 'Remote Type'), ('job_category', 'Job Category')], max_length=255, null=True)),
            ],
            options={
                'db_table': 'applicant_config',
                'description': 'Applicant Configuration',
                'unique_together': {('field_name', 'value')},
            },
        ),
        migrations.CreateModel(
            name='JobQuestionTemplateConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('write_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_uid', models.IntegerField(blank=True, editable=False, null=True)),
                ('write_uid', models.IntegerField(blank=True, editable=False, null=True)),
                ('create_ucp_id', models.CharField(blank=True, editable=False, null=True)),
                ('write_ucp_id', models.CharField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('template_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted')], default='INACTIVE', max_length=50, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
            ],
            options={
                'db_table': 'job_question_template_config',
                'description': 'Job Question Template Config Model',
            },
        ),
        migrations.CreateModel(
            name='JobQuestionConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question_title', models.TextField()),
                ('question_type', models.CharField(choices=[('TEXT', 'Text'), ('SINGLE_CHOICE', 'Single Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice')], default='TEXT', max_length=50)),
                ('choices', models.JSONField(blank=True, default=list, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='configuration.jobquestiontemplateconfigmodel')),
            ],
            options={
                'db_table': 'job_question_config',
                'description': 'Job Question Config Model',
            },
        ),
    ]
