# Generated by Django 5.1.6 on 2025-12-11 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_oauth', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='companies', to='base.company', verbose_name='list of companies'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='education',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_institution', to='base.institution'),
        ),
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_location', to='base.geoarea'),
        ),
        migrations.AddField(
            model_name='permission',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_oauth.permission'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_company', to='base.company'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_location', to='base.geoarea'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_user_profile', to='auth_oauth.profile'),
        ),
        migrations.AddField(
            model_name='link',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_user_profile', to='auth_oauth.profile'),
        ),
        migrations.AddField(
            model_name='education',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_user_profile', to='auth_oauth.profile'),
        ),
        migrations.AddField(
            model_name='profiledocumentmodel',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='Profile that owns this document.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='auth_oauth.profile'),
        ),
        migrations.AddField(
            model_name='profilelanguage',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_language', to='base.language'),
        ),
        migrations.AddField(
            model_name='profilelanguage',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_language_user', to='auth_oauth.profile'),
        ),
        migrations.AddField(
            model_name='reference',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_company', to='base.company'),
        ),
        migrations.AddField(
            model_name='reference',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_user_profile', to='auth_oauth.profile'),
        ),
        migrations.AddField(
            model_name='role',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_company', to='base.company'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions_related', to='auth_oauth.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='auth_oauth.role'),
        ),
        migrations.AddField(
            model_name='skill',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_user_profile', to='auth_oauth.profile'),
        ),
        migrations.AddField(
            model_name='userauthenticationsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercompanyprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_company_profile_company', to='base.company'),
        ),
        migrations.AddField(
            model_name='usercompanyprofile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_oauth.usercompanyprofile'),
        ),
        migrations.AddField(
            model_name='usercompanyprofile',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_oauth.profile'),
        ),
        migrations.AddField(
            model_name='usercompanyprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='roles_related', to='auth_oauth.role'),
        ),
        migrations.AddField(
            model_name='usercompanyprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_company_profile_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userauthenticationsession',
            name='user_company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_user_company_profile', to='auth_oauth.usercompanyprofile'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_experience_company', to='base.company'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_experience_location', to='base.geoarea'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_experience_user_profile', to='auth_oauth.profile'),
        ),
        migrations.AddConstraint(
            model_name='profiledocumentmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('is_deleted', False)), fields=('profile', 'document_type'), name='unique_default_doc_per_type'),
        ),
    ]
