# Generated by Django 5.1.6 on 2026-03-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_oauth', '0003_user_base_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_link_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
