# Generated by Django 5.1.6 on 2026-05-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostmodel',
            name='is_pipeline_visible',
            field=models.BooleanField(default=True, help_text='To decide whether applicants can see the pipeline when create a job post'),
        ),
    ]
