# Generated by Django 5.1.6 on 2026-05-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management_app', '0002_jobpostmodel_is_pipeline_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostmodel',
            name='is_pipeline_visible',
            field=models.BooleanField(default=False, help_text='To decide whether applicants can see the pipeline when create a job post'),
        ),
    ]
