# Generated by Django 5.1.6 on 2026-05-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management_app', '0003_alter_jobpostmodel_is_pipeline_visible'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobapplicationmodel',
            name='ux_jobapp_ucp_job_active_only',
        ),
        migrations.AddField(
            model_name='jobapplicationmodel',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted'), ('DRAFT', 'Draft'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=50, null=True),
        ),
    ]
