# Generated by Django 5.1.6 on 2026-05-14 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management_app', '0004_remove_jobapplicationmodel_ux_jobapp_ucp_job_active_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostmodel',
            name='reposted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpostmodel',
            name='reposted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='job_management_app.jobpostmodel'),
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DELETED', 'Deleted'), ('DRAFT', 'Draft'), ('CLOSED', 'Closed'), ('PUBLISHED', 'Published'), ('SCHEDULED', 'Scheduled')], default='ACTIVE', max_length=50, null=True),
        ),
    ]
