# Generated by Django 5.1.6 on 2026-06-01 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_oauth', '0004_user_phone_number_user_telegram_chat_id_and_more'),
        ('job_management_app', '0005_jobpostmodel_reposted_at_jobpostmodel_reposted_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostAssignedRecruiterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('write_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_uid', models.IntegerField(blank=True, editable=False, null=True)),
                ('write_uid', models.IntegerField(blank=True, editable=False, null=True)),
                ('create_ucp_id', models.CharField(blank=True, editable=False, null=True)),
                ('write_ucp_id', models.CharField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_ucp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_job_posts', to='auth_oauth.usercompanyprofile')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_assigned_recruiters', to='job_management_app.jobpostmodel')),
            ],
            options={
                'db_table': 'job_post_assigned_recruiter',
            },
        ),
        migrations.AddField(
            model_name='jobpostmodel',
            name='assigned_recruiters',
            field=models.ManyToManyField(blank=True, related_name='+', through='job_management_app.JobPostAssignedRecruiterModel', to='auth_oauth.usercompanyprofile'),
        ),
    ]
