# Generated by Django 5.1.6 on 2026-05-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management_app', '0005_jobpostmodel_reposted_at_jobpostmodel_reposted_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationmodel',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
