# Generated by Django 5.1.6 on 2026-06-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_management_app', '0006_jobapplicationmodel_code'),
        ('job_management_app', '0006_jobpostassignedrecruitermodel_and_more'),
    ]

    operations = [
    ]
