[global]
index-url = https://pypi.org/simple
extra-index-url = https://USERNAME:PASSWORD@stage-nexus.wingbank.com/repository/wdg-core/simple
trusted-host =stage-nexus.wingbank.com pypi.org

[user]
trusted-host = pypi.org
