# Generated by Django 5.1.6 on 2026-06-10 03:36

import apps.integration.utils.crypto_utils
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationHandshake',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('write_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_uid', models.IntegerField(blank=True, editable=False, null=True)),
                ('write_uid', models.IntegerField(blank=True, editable=False, null=True)),
                ('create_ucp_id', models.CharField(blank=True, editable=False, null=True)),
                ('write_ucp_id', models.CharField(blank=True, editable=False, null=True)),
                ('temporary_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
                ('code_challenge', models.CharField(max_length=128)),
                ('organization_id', models.CharField(db_index=True, max_length=100)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
            ],
            options={
                'db_table': 'integrate_handshakes',
            },
        ),
        migrations.CreateModel(
            name='IntegrationPartner',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('write_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_uid', models.IntegerField(blank=True, editable=False, null=True)),
                ('write_uid', models.IntegerField(blank=True, editable=False, null=True)),
                ('create_ucp_id', models.CharField(blank=True, editable=False, null=True)),
                ('write_ucp_id', models.CharField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.CharField(max_length=100, unique=True)),
                ('partner_tenant_id', models.CharField(max_length=100)),
                ('partner_outbound_key', apps.integration.utils.crypto_utils.EncryptedTextField()),
                ('partner_outbound_hash', models.CharField(max_length=64, unique=True)),
                ('partner_inbound_key', apps.integration.utils.crypto_utils.EncryptedTextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('disconnected', 'Disconnected'), ('revoked', 'Revoked'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
            ],
            options={
                'db_table': 'integrate_partner',
            },
        ),
        migrations.CreateModel(
            name='IntegrationUserMapping',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('write_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_uid', models.IntegerField(blank=True, editable=False, null=True)),
                ('write_uid', models.IntegerField(blank=True, editable=False, null=True)),
                ('create_ucp_id', models.CharField(blank=True, editable=False, null=True)),
                ('write_ucp_id', models.CharField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_user_id', models.CharField(max_length=100)),
                ('partner_user_id', models.CharField(max_length=100)),
                ('company', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mappings', to='integration.integrationpartner')),
            ],
            options={
                'db_table': 'integrate_user_mappings',
                'unique_together': {('connection', 'local_user_id')},
            },
        ),
    ]
