# Generated by Django 5.1.6 on 2026-06-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationhandshake',
            name='redirect_uri',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterModelTable(
            name='integrationhandshake',
            table='integrate_handshakes',
        ),
    ]
