# Generated by Django 5.1.6 on 2025-12-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('write_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_uid', models.IntegerField(blank=True, editable=False, null=True)),
                ('write_uid', models.IntegerField(blank=True, editable=False, null=True)),
                ('app_name', models.CharField(blank=True, choices=[('auth_totp_mail', 'AUTH TOTP MAIL'), ('auth_totp_mfa', 'AUTH TOTP MFA')], default='auth_totp_mail', max_length=100, null=True)),
                ('is_enable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Auth Setting',
                'verbose_name_plural': 'Auth Setting',
                'db_table': 'auth_setting',
            },
        ),
    ]
